### ISSUE TITLE
你好，我问下，关于主页的路由怎么填

### ISSUE THREAD

**Issue by yoke1990** [nikoloss/iceworld#1]
@Router.route(url=r"", method=Router._GET | Router._POST)
def home(self,req):
我设置为空，为/都不行

例如，我访问这个，就能打开home
http://localhost:8888/

**Comment by nikoloss** [comment]
您好，首先非常感谢您的关注。的确是我没有考虑到，以为这个项目我是一直当作api站来做的所以在正则捕获路径参数的时候忽略了最前面的那个“/”。现在修改了一下，不忽略最前面的/ ，如此一来在配置路由的时候就必须要写最前面的/符号了，切记切记！：）
